### ISSUE TITLE
Stopped working on jira data-version="8.20.6"

### ISSUE THREAD

**Issue by andersvold** [SethSilverBeard/jira-awesomizer-defaults#4] opened 2022-03-15 12:20 UTC
I cant seem to get this awesome plugin to work any more.

Inspected Jira, and data-version="8.20.6"

<meta name="application-name" content="JIRA" data-name="jira" data-version="8.20.6">

**Comment by SethSilverBeard** [comment] 2022-04-11 03:13
Oh bummer! I don't have 8.20.6 to test against but working on it - I reapplied for an open source license from Atlassian so I can download and run. Crossing my fingers its approved.

I did get the Cloud version (their latest) and they completely switched the Javascript backend to ReactJS, so that may require a huge overhaul in future.

**Comment by andersvold** [comment] 2022-04-19 16:28
@SethSilverBeard thanks for helping out.
Do you know where in the script I could try to locate the issues?
Right now, nothing happens when I use the script in Tampermonkey-plugin with chrome. Everything was fine before

**Comment by andersvold** [comment] 2022-04-19 16:29
I also thought jira had a way of setting up parameters in the URL for creating new issues.... But havent figured out how. And Jira Awesomizer was so easy to use
Something like: CreateIssueDetails!init.jspa?pid=10031&issuetype=13&customfield_10017=3&customfield_10116=203

**Comment by SethSilverBeard** [comment] 2022-04-20 20:40
Ok! I got 8.20.6 installed locally and can't reproduce the issue. Few things to help debug:
1) Be sure you're on 1.0.3 of the JIRA Awesomizer.
2) Can you manually execute the script? Try this button: 
![image](https://user-images.githubusercontent.com/15022238/164318321-dfb056d7-88fc-41cb-8355-a6c9abde9b4d.png). If nothing happens, open Chrome Dev Tools console using F12 and see if there's any output.
* Note if you dont have the option to do this, try adding your URL to the @include option per the FAQ num 2: https://github.com/SethSilverBeard/jira-awesomizer-defaults#faqs

**Comment by SethSilverBeard** [comment] 2022-04-20 21:37
Ah I got an error when loading some saved defaults! So "Create Issue" just hangs, and I get this error in F12 Developer Console. Is it same as yours?
```js
userscript.html?name=Jira%2520Awesomizer%2520Defaults.user.js&id=8f7db28b-1ff7-4822-ba34-0ad8382c6b5d:172 Uncaught TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Map (<anonymous>)
    at fetchStoredAwesomeDefaults (userscript.html?name=Jira%2520Awesomizer%2520Defaults.user.js&id=8f7db28b-1ff7-4822-ba34-0ad8382c6b5d:172:12)
    at main (userscript.html?name=Jira%2520Awesomizer%2520Defaults.user.js&id=8f7db28b-1ff7-4822-ba34-0ad8382c6b5d:60:18)
```

**Comment by SethSilverBeard** [comment] 2022-04-22 21:10
Alright! Bug should be fixed, please update your script to new version 1.0.4. Thanks for finding and reporting this @andersvold .

**Closed as completed by SethSilverBeard** 2022-04-22 21:10 UTC

**Comment by JSmith-JDECoffee** [comment] 2023-09-25 10:04
> Oh bummer! I don't have 8.20.6 to test against but working on it - I reapplied for an open source license from Atlassian so I can download and run. Crossing my fingers its approved.
> 
> I did get the Cloud version (their latest) and they completely switched the Javascript backend to ReactJS, so that may require a huge overhaul in future.

Hi,

So I previously used this on another JIRA instance and loved it, I was trying to figure out why it doesn't work on the current JIRA I have at a client and it looks like its cause its the Cloud version (1001.0.0-SNAPSHOT).

I would assume you have not since tried updating to deal with the ReactJS version and I am kind of screwed right?

**Comment by SethSilverBeard** [comment] 2023-09-26 03:15
Correct, it's not been updated for ReactJS and I don't have time these days
to support it. This plugin filled a gap for a good 7 years, I'm
disappointed Atlassian still hasn't made default values a built in feature.

**Comment by JSmith-JDECoffee** [comment] 2023-09-26 07:09
Understandable and I fully agree, absurd that Atlassian still havent done it, your extension worked great and now and sorely miss it. Thanks for the effort you made to build and share it.
